progress on #4 auto dev env setup

diff --git a/ci b/ci
--- a/ci
+++ b/ci
@@ -12,8 +12,12 @@ log:info() { local args=$@
     echo $@
 }
 
+log:warn() { local args=$@
+    echo "WARN: $@"
+}
+
 log:error() { local args=$@
-    echo "ERROR: ${@}"
+    echo "ERROR: $@"
 }
 
 bash:command:exists() { local commandName=$1
@@ -88,26 +92,46 @@ docker:machine() { local args=$@
     docker-machine ${args}
 }
 
-docker:machine:name() {
+docker:machine:host:name() {
     echo "react-express-typescript"
 }
 
-docker:machine:isHostDefined() {
-    set -e
-    docker:machine:install
-    local dockerHostDef="$(docker-machine ls | grep $(docker:machine:name))"
-    string:notEmpty "${dockerHostDef}"
+docker:machine:host:isDefined() {
+    string:notEmpty "$(docker:machine ls --filter name=$(docker:machine:host:name) --quiet)"
 }
 
-docker:machine:createHost() {
-    set -e
-    if ! docker:machine:isHostDefined; then
-        docker:machine create "$(docker:machine:name)" --driver virtualbox
+docker:machine:host:isRunning() {
+    string:notEmpty "$(docker:machine ls --filter name=$(docker:machine:host:name) --filter state=Running --quiet)"
+}
+
+docker:machine:host:create() {
+    if ! docker:machine:host:isDefined; then
+        docker:machine create $(docker:machine:host:name) --driver virtualbox
+    fi
+}
+
+docker:machine:host:start() {
+    docker:machine:host:create
+    if ! docker:machine:host:isRunning; then
+        docker:machine start $(docker:machine:host:name)
+    fi
+}
+
+docker:machine:host:stop() {
+    if docker:machine:host:isRunning; then
+        docker:machine stop $(docker:machine:host:name)
+    fi
+}
+
+docker:machine:host:delete() {
+    if docker:machine:host:isDefined; then
+        docker:machine:host:stop
+        docker:machine rm -y $(docker:machine:host:name)
     fi
 }
 
 docker:machine:connectClient() {
-    eval $(docker:machine env "$(docker:machine:name)")
+    eval $(docker:machine env "$(docker:machine:host:name)")
 }
 
 docker:install() {
@@ -118,7 +142,7 @@ docker:install() {
 }
 
 docker:cli() { local args=$@
-    docker:machine:createHost
+    docker:machine:host:start
     docker:machine:connectClient
     docker ${args}
 }
@@ -139,11 +163,27 @@ docker:run() { local imageName=$1; local tag=$2; local args=${@:3}
     docker:cli run "${imageName}:${tag}" ${args}
 }
 
-dev:environment:start() {
-    local tag="$(docker:build:tag:forLocalDev)"
-    local imageName="react-express-typescript-dev-environment"
-    docker:buildAndTag ${imageName} ${tag} ./Dockerfile .
-    docker:run ${imageName} ${tag}
+bash:runInBackground() { local logFile=$1; local command=${@:2}; export clearLogs
+    log:info "Running ${command} in background. Logs written to ${logFile}..."
+    if string:notEmpty "${clearLogs}"; then
+        rm "${logFile}"
+    fi
+     $command >> "${logFile}" 2>&1 &
+}
+
+dev:environment:runEverything() {
+    dev:environment:stopEverything
+    mkdir -p logs
+    dev:environment:docker:run:mounted "$(dev:environment:docker:baseImage)" npm i
+    dev:environment:docker:run:mounted "$(dev:environment:docker:baseImage)" echo "docker container is ready and working..."
+    bash:runInBackground "logs/tsc.log" dev:environment:tscWatch
+    bash:runInBackground "logs/webpack.log" dev:environment:webpackWatch
+    bash:runInBackground "logs/express.log" dev:environment:express:run
+    dev:browser:open
+}
+
+dev:environment:stopEverything() {
+    docker:machine:host:delete
 }
 
 dev:environment:docker:baseImage() {
@@ -171,11 +211,59 @@ dev:environment:express:run() {
 }
 
 docker:machine:ip() {
-    docker:machine inspect --format='{{.Driver.IPAddress}}' "$(docker:machine:name)"
+    docker:machine inspect --format='{{.Driver.IPAddress}}' "$(docker:machine:host:name)"
 }
 
-dev:browser() {
-    open "http://$(docker:machine:ip):3000"
+retry:until:returnsNonEmptyString() { local numberOfTimes=$1; local secondsBetweenTries=$2; local command=${@:3}
+    #TODO: do not output twice
+    local timesRemaining=$numberOfTimes
+    local conditionMet=false
+    until strings:areEqual $conditionMet true; do
+        local output=$($command)
+        if string:notEmpty $output; then
+            conditionMet=true
+        else
+            sleep ${secondsBetweenTries}
+            timesRemaining=$(($timesRemaining - 1))
+            if [ "$timesRemaining" -eq 0 ]; then
+                log:error "$numberOfTimes retries exceeded in function retry:until:returnsNonEmptyString for command: ${command}"
+                exit 1
+            fi
+        fi
+    done
+    echo $output
+}
+
+strings:areEqual() { local s1=$1; local s2=$2
+    [ "${s1}" == "${s2}" ]
+}
+
+emptyStringIfCommandFails() { local command=$@
+    eval $command > /dev/null 2>&1
+    if strings:areEqual $? '0'; then
+        echo "success"
+    else 
+        echo ""
+    fi
+}
+
+retry:until:command:isSuccessful() { local numberOfTimes=$1; local secondsBetweenTries=$2; local command=${@:3}
+    retry:until:returnsNonEmptyString $numberOfTimes $secondsBetweenTries emptyStringIfCommandFails $command
+}
+
+command:returnsNonEmptyString() { local command=$@
+    string:notEmpty $($command)
+}
+
+command:isSuccessful() { local command=$@
+    eval $command
+}
+
+dev:browser:open() {
+    local host="$(retry:until:returnsNonEmptyString 20 1 docker:machine:ip)"
+    local siteURL="http://${host}:3000"
+    dev:environment:docker:run:mounted $(dev:environment:docker:baseImage) ./ci retry:until:command:isSuccessful 20 1 curl ${siteURL}
+    open $siteURL
 }
 
 ci:functions:list() {
